export const citas = [
  {
    id: 1,
    cliente: 'Juan Pérez',
    telefono: '600123456',
    servicio: 'Corte de pelo',
    variante: 'Clásico',
    sucursal: 'Centro',
    profesional: 'Ana Ruiz',
    fecha: '2024-07-20',
    hora: '09:00',
    descuentos: '10%',
  },
  {
    id: 2,
    cliente: 'María López',
    telefono: '600987654',
    servicio: 'Coloración',
    variante: 'Balayage',
    sucursal: 'Norte',
    profesional: 'Luis García',
    fecha: '2024-07-20',
    hora: '10:30',
    descuentos: '0%',
  },
  {
    id: 3,
    cliente: 'Carlos Díaz',
    telefono: '600555888',
    servicio: 'Manicura',
    variante: 'Gel',
    sucursal: 'Sur',
    profesional: 'Marta Pérez',
    fecha: '2024-07-20',
    hora: '12:00',
    descuentos: '15%',
  },
];
